# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\Users\Cristiano\Desktop\conda-circle-fitting-3d\circle-fitting-3d, last modified Thu Aug 11 11:07:40 2022
# ------------------------------------------------

package:
  name: circle-fitting-3d
  version: 1.0.0
source:
  sha256: 8d2b989f293eec9c6f33a6025e77779d1aa805c90a960332d0894ee591180668
  url: https://pypi.io/packages/source/c/circle-fitting-3d/circle-fitting-3d-1.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: C:\\Users\\Cristiano\\anaconda3\\conda-bld\\circle-fitting-3d_1660211685777\\_h_env\\python.exe
    -m pip install . -vv
  string: py_0
requirements:
  host:
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2022.6.15 h5b45459_0
    - libffi 3.4.2 h8ffe710_5
    - libzlib 1.2.12 h8ffe710_2
    - openssl 3.0.5 h8ffe710_1
    - pip 22.2.2 pyhd8ed1ab_0
    - python 3.10.5 hcf16a7b_0_cpython
    - python_abi 3.10 2_cp310
    - setuptools 63.4.3 py310h5588dad_0
    - sqlite 3.39.2 h8ffe710_0
    - tk 8.6.12 h8ffe710_0
    - tzdata 2022a h191b570_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_6
    - vs2015_runtime 14.29.30037 h902a5da_6
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h62dcd97_1
  run:
    - python >=3.7
    - scikit-spatial >=1.0.1
test:
  commands:
    - pip check
  imports:
    - circle_fitting_3d
  requires:
    - pip
about:
  home: https://pypi.org/project/circle-fitting-3d/
  license: BSD-2-Clause
  license_file:
    - LICENSE
  summary: This package allows to compute the best fit circle given points in three-dimensional
    space.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AddYourGitHubIdHere
